Dev/bap wps onboarding
prplfoundation/prplMesh pull request #1096
Opened 2020-04-06 01:23 UTC by tomereli

2020-04-08 12:37 UTC, arnout requested changes
Looks good to me so far. I think actually this is enough for a PR to get merged right away, even if the dwpal implementation is incomplete or doesn't work yet.

That said, I would like to re-review the final version, so changes requested.

2020-04-08 12:37 UTC, arnout commented on agent/src/beerocks/slave/agent_ucc_listener.cpp
> +    }
(nitpick) I think it's better to do this in beerocks_ucc_listener. We do that for the other commands as well.

2020-04-08 12:37 UTC, arnout commented on common/beerocks/tlvf/yaml/beerocks/tlvf/beerocks_message_backhaul.yaml
> +  _type: class
Newline at end of file.

More importantly though: the band will definitely need to be part of this message. Or perhaps the radio_uid. Or the bssid. For sure, *something* :-)

2020-04-08 12:37 UTC, arnout commented on agent/src/beerocks/slave/agent_ucc_listener.cpp
> +    }
In my version of the test plan, there is an `interface` parameter, not a `band` parameter...

But... This is f**ing marvelous... UCC indeed uses the band parameter, not the interface parameter. So the test plan is apparently just informational :-(

2020-04-08 12:37 UTC, arnout commented on agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp
> +bool backhaul_manager::start_wps_pbc(bool is_5ghz)
I would like to avoid (new) boolean values for the band, because at some point we might support 60GHz, and I'm not sure if 6GHz is going to be treated as a separate band or not.

So, prefer to use an enum or maybe even bitmask here.

That said, I think this `band` is just an artefact of UCC. I think in the high-level API, we'll want to be able to start PBC either on all radios or on a single radio, or maybe a list of radios. So I think it's better that we resolve the radio(s) in the ucc listener and that backhaul_manager::start_wps_pbc takes the radio(s) as argument.

2020-04-08 12:37 UTC, arnout commented on agent/src/beerocks/slave/agent_ucc_listener.cpp
> +    return m_backhaul_manager_ctx.start_wps_pbc(band->second == "5G");
If it returns false, err_string should be set to something.

2020-04-08 12:37 UTC, arnout commented on common/beerocks/bwl/include/bwl/ap_wlan_hal.h
> +    virtual bool start_wps_pbc() = 0;
In general, it is possible (and likely) that WPS is started on several radios simultaneously. In that case, we need to make sure that they use the same UUID. I think the only way to do that is to generate the UUID from prplmesh and pass it here.

Note that we don't need to implement generating the UUID yet - that would be an M3 feature. However, for the bwl it is better to have the interface as complete as possible already from the start - bwl changes are annoying for integrators. So, please allow a UUID as an optional parameter here.

2020-04-08 12:37 UTC, arnout commented on common/beerocks/bwl/dummy/ap_wlan_hal_dummy.cpp
> +    // TODO - simulate client connected?
For dummy, the minimal implementation is to write something to the log. Then you don't need a todo.

2020-04-19 07:02 UTC, tomereli commented on common/beerocks/tlvf/yaml/beerocks/tlvf/beerocks_message_backhaul.yaml
> +  _type: class
Ehmm, why? The backhaul manager sends this message to a single radio agent, the one which should start WPS, so radio_uid is not needed.

2020-04-20 06:44 UTC, tomereli commented on common/beerocks/tlvf/yaml/beerocks/tlvf/beerocks_message_backhaul.yaml
> +  _type: class
Fixed the newline.
Add radio id and bssid on which to trigger wps.

2020-04-20 06:53 UTC, tomereli commented on common/beerocks/bwl/include/bwl/ap_wlan_hal.h
> +    virtual bool start_wps_pbc() = 0;
I don't understand - the hostapd API doesn't support adding UUID, so where will it be used? Also what is the UUID type? I think this should be done in a separate PR anyway.

2020-04-30 17:51 UTC, tomereli commented
Re-opened since with this, autoconfiguration seems to work on the backhaul VAP, compared to https://github.com/prplfoundation/prplMesh/pull/1168 which fails. Will rebase this PR to see if the reason is something with the recent prplMesh changes.

2020-05-03 15:59 UTC, vitalybu commented on agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp
> +    auto slave = *it;
Why do you need another variable in the way?

2020-05-03 15:59 UTC, vitalybu commented on agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.h
> +    const std::string freq_to_radio_mac(enum eFreqType freq) const;
```suggestion
    const std::string freq_to_radio_mac(eFreqType freq) const;
```

2020-05-03 15:59 UTC, vitalybu commented on agent/src/beerocks/slave/ap_manager_thread.cpp
> +            return false;
I don't think you should return `false` here (it's for critical errors only).
If there's no response message, just `break`.

2020-05-03 15:59 UTC, vitalybu commented on agent/src/beerocks/slave/ap_manager_thread.cpp
> +        ap_wlan_hal->start_wps_pbc(vap_name);
This call can also fail

2020-05-03 15:59 UTC, vitalybu commented on common/beerocks/bwl/econet/ap_wlan_hal_econet.h
> +    update_vap_credentials(std::list<son::wireless_utils::sBssInfoConf> &bss_info_conf_list,
Forgot the `start_wps_pbc` override:
```c++
virtual bool start_wps_pbc(const std::string &iface_name) override;
```

2020-05-03 15:59 UTC, vitalybu commented on common/beerocks/bwl/dwpal/ap_wlan_hal_dwpal.cpp
> +    std::string bssid, ifname;
(nitpick)
```suggestion
    std::string bssid;
```

2020-05-03 15:59 UTC, vitalybu commented on common/beerocks/bwl/dwpal/ap_wlan_hal_dwpal.cpp
> +    if (!hostapd_config_get_value(vap_hostapd_config, "bss", ifname)) {
(nitpick)
```suggestion

    std::string ifname;
    if (!hostapd_config_get_value(vap_hostapd_config, "bss", ifname)) {
```

2020-05-03 16:52 UTC, tomereli commented
Obsolete - replaced by #1168

2020-05-03 16:52 UTC, closed without merging