[WIP] Feature/shell scripts cleanup
prplfoundation/prplMesh pull request #1103
Opened 2020-04-07 05:21 UTC by MuteSpirit

2020-04-08 12:43 UTC, arnout commented
Please make a PR that just does the removals so we can already merge it.

2020-04-09 12:52 UTC, arnout requested changes
tests/openwrt/test_status.sh is actually used by openwrt, so that one has to stay.

docker-builder.sh and docker-runner.sh are scripts that I don't use myself, but maybe other people do? Anyway they're trivial to fix so I don't think we really need to remove them.

Please don't set the Ready for merge label until at least Alex or Adam, Raphaél, and Tomer have reviewed it. We want to be sure that really nobody uses these scripts!

2020-04-09 14:59 UTC, rmelotte approved these changes

2020-04-10 08:24 UTC, adam1985d requested changes
please do not remove this file yet
this file is a reference file to "how to configure `stand-alone-repeater` mode in Intel CGR platform"

it should not be part of prplmesh - but should be moved to RDKB recipe instead of just remove.
I created a task to move it to RDKB recipe which will also remove it from prplmesh (#1128 ) - please don't remove it as part of your PR
@tomereli @kantera800

2020-04-12 04:16 UTC, adam1985d approved these changes

2020-04-14 07:52 UTC, tomereli approved these changes

2020-04-14 13:21 UTC, arnout approved these changes

2020-04-14 14:35 UTC, merged