CODINGSTYLE.md: Add multiple vs single point of exit
prplfoundation/prplMesh pull request #1115
Opened 2020-04-07 15:43 UTC by tomereli

Based on the poll done in #prplmesh-democracy on slack, the majority
prefers to use multiple points of exit from functions.
Add a section for this in CODINGSTYLE.md which explains the pros and
cons of using single point of exit vs multiple points of exit, with
examples and which pattern we expect contributors to use.

2020-04-07 16:45 UTC, vitalybu requested changes

2020-04-07 16:45 UTC, vitalybu commented on CODINGSTYLE.md
> +}
Your function returns an `int` but internally use return `true`/`false` :)
Consider adding another good example:
```cpp
bool func(int arg1)
{
    // validate arguments
    if (arg1 < 0) {
        return false;
    }

    // do something

    return true;
}
```

The idea is to not use an `else` clause in this case to reduce indentation levels.

2020-04-07 16:45 UTC, vitalybu commented on CODINGSTYLE.md
> +  return result;
Be consistent in your examples. Either use 2 or 4 (preferably) spaces for indentation.

2020-04-07 17:39 UTC, vitalybu approved these changes

2020-04-08 07:56 UTC, rmelotte approved these changes

2020-04-08 07:56 UTC, rmelotte commented on CODINGSTYLE.md
> +Another advantage of using multiple points of exit is that you can check preconditions and exit early at the start of a function, so that you know in the body of the function that certain conditions
Please split this to have one sentence per line, it's in CODINGSTYLE.md already :-) 
>Lines in markdown documents are not wrapped, but every sentence should start on a new line.

2020-04-08 07:56 UTC, rmelotte commented on CODINGSTYLE.md
> +    }
IMO this doesn't really show your point of keeping the indentation level low or checking arguments early, so maybe we should keep only the other example.
On the other hand, it shows what having multiple points of exit _means_, I guess that's why you did it like this.

2020-04-08 10:41 UTC, merged