Dev/tlvf variable length list support
prplfoundation/prplMesh pull request #114
Opened 2019-07-17 20:02 UTC by tomereli

2019-07-17 21:35 UTC, tomereli commented
![Screenshot from 2019-07-18 00-33-01](https://user-images.githubusercontent.com/13386849/61413327-de344e80-a8f3-11e9-8c3b-1f21213b4d1f.png)

2019-07-18 04:49 UTC, LiorAmram requested changes

2019-07-18 04:49 UTC, LiorAmram commented on framework/tlvf/tlvf.py
>                  if param_type and param_type.startswith("e"):
this line should be replaced with:
`if TypeInfo(param_type).type == TypeInfo.ENUM`
That provides you the functionality you implemented in the following lines.

2019-07-18 10:18 UTC, morantr requested changes
memmove() is banned function. according to: 
https://github.com/intel/safestringlib/wiki/SDL-List-of-Banned-Functions
Use instead std::move()
http://www.cplusplus.com/reference/algorithm/move/

2019-07-18 10:49 UTC, morantr submitted a review, later dismissed
What about all the class members pointers that are allocated after the list?
I mean, they are set to a specific location on the buffer on the init function. And they are still pointing to the same place after you moved the memory. Changing them will still create a data override.

2019-07-18 11:53 UTC, tomereli commented
> memmove() is banned function. according to:
> https://github.com/intel/safestringlib/wiki/SDL-List-of-Banned-Functions
> Use instead std::move()
> http://www.cplusplus.com/reference/algorithm/move/

C memmove is banned - C++ std::memmove is fine (basically all of the STL APIs pass SDL)

2019-07-18 11:56 UTC, tomereli commented
> What about all the class members pointers that are allocated after the list?
> I mean, they are set to a specific location on the buffer on the init function. And they are still pointing to the same place after you moved the memory. Changing them will still create a data override.

They are handled in the alloc function - read the commit description - when we build the alloc function in the TLVF, we add the `std::memmove` and add a special comment, "marker", that is later used when we are adding the parameters that come after the list. For each such parameter we add code using the marker to update the pointer before the `std::memmove`.

I have a bug which @LiorAmram pointed out - when the list element type is a class, we don't do that - if this is what you refer to then nice catch! I'll fix it in a followup commit.

2019-07-18 12:16 UTC, morantr commented
> > memmove() is banned function. according to:
> > https://github.com/intel/safestringlib/wiki/SDL-List-of-Banned-Functions
> > Use instead std::move()
> > http://www.cplusplus.com/reference/algorithm/move/
> 
> C memmove is banned - C++ std::memmove is fine (basically all of the STL APIs pass SDL)

According to here:
https://stackoverflow.com/questions/8380805/difference-between-string-h-and-cstring
it is said that:
"Table 55 describes the header <cstring>.
The contents are the same as the Standard C library header , with the change to memchr() specified in 21.7."

So basically it is the same C function with small change. I still think it is better to use std::move instead, it is more cpp way.

2019-07-18 12:25 UTC, morantr commented
> > What about all the class members pointers that are allocated after the list?
> > I mean, they are set to a specific location on the buffer on the init function. And they are still pointing to the same place after you moved the memory. Changing them will still create a data override.
> 
> They are handled in the alloc function - read the commit description - when we build the alloc function in the TLVF, we add the `std::memmove` and add a special comment, "marker", that is later used when we are adding the parameters that come after the list. For each such parameter we add code using the marker to update the pointer before the `std::memmove`.
> 
> I have a bug which @LiorAmram pointed out - when the list element type is a class, we don't do that - if this is what you refer to then nice catch! I'll fix it in a followup commit.

Well, I looked at the generated code of list class type and didn't see that the member pointers are moved. So yes I meant that.


.

2019-07-18 14:19 UTC, LiorAmram commented
This [issue](https://github.com/prplfoundation/prplMesh/issues/115) should be addressed in the future.
For now it's OK to keep it as a working standard.

2019-07-19 12:25 UTC, LiorAmram requested changes

2019-07-19 12:25 UTC, LiorAmram commented on framework/tlvf/tlvf.py
> +                param_meta.list_index = obj_meta.list_index
This mechanism should also be added to dynamic lists (is_dynamic_len - unknown list length).

2019-07-19 12:25 UTC, LiorAmram commented on framework/tlvf/tlvf.py
> +                    lines_cpp.append( "%s} else {" %self.getIndentation(1))
'else' section is unnecessary, because of the return statement.

2019-07-19 12:25 UTC, LiorAmram commented on framework/tlvf/tlvf.py
> +                    lines_cpp.append( "%sm_%s__ = %s;" %(self.getIndentation(2), self.MEMBER_LOCK_ORDER_COUNTER, param_meta.list_index) )
Might be better to first make all sanity tests (count == 0 and available space on buffer) and only then update the counter.

2019-07-19 12:25 UTC, LiorAmram commented on framework/tlvf/tlvf.py
> +                    lines_cpp.append( "%sif (m_%s__ > %s) {;" %(self.getIndentation(1), self.MEMBER_LOCK_ORDER_COUNTER, param_meta.list_index) )
remove semicolon at the end of this line

2019-07-19 12:25 UTC, LiorAmram commented on framework/tlvf/tlvf.py
> +                    lines_cpp.append( "%s} else {" %self.getIndentation(1))
same - remove else

2019-07-19 12:25 UTC, LiorAmram commented on framework/tlvf/tlvf.py
> +                    lines_cpp.append( "%sm_%s__ = %s;" %(self.getIndentation(2), self.MEMBER_LOCK_ORDER_COUNTER, param_meta.list_index) )
same

2019-07-19 13:18 UTC, tomereli commented
> memmove() is banned function. according to:
> https://github.com/intel/safestringlib/wiki/SDL-List-of-Banned-Functions
> Use instead std::move()
> http://www.cplusplus.com/reference/algorithm/move/

Done

2019-07-19 13:21 UTC, tomereli commented
> > > What about all the class members pointers that are allocated after the list?
> > > I mean, they are set to a specific location on the buffer on the init function. And they are still pointing to the same place after you moved the memory. Changing them will still create a data override.
> > 
> > 
> > They are handled in the alloc function - read the commit description - when we build the alloc function in the TLVF, we add the `std::memmove` and add a special comment, "marker", that is later used when we are adding the parameters that come after the list. For each such parameter we add code using the marker to update the pointer before the `std::memmove`.
> > I have a bug which @LiorAmram pointed out - when the list element type is a class, we don't do that - if this is what you refer to then nice catch! I'll fix it in a followup commit.
> 
> Well, I looked at the generated code of list class type and didn't see that the member pointers are moved. So yes I meant that.
> 
> .

It all works fine now. Generated code does update the flag:
```
bool cPreferenceOperatingClasses::alloc_channel_list(size_t count) {
    if (m_lock_order_counter__ > 0) {;
        TLVF_LOG(ERROR) << "Out of order allocation for variable length list channel_list, abort!";
        return false;
    } else {
        m_lock_order_counter__ = 0;
    }
    if (count == 0) {
        TLVF_LOG(WARNING) << "can't allocate 0 bytes";
        return false;
    }
    size_t len = sizeof(uint8_t) * count;
    if(getBuffRemainingBytes() < len )  {
        TLVF_LOG(ERROR) << "Not enough available space on buffer - can't allocate";
        return false;
    }
    if (!m_parse__) {
        uint8_t *src = (uint8_t *)m_channel_list;
        uint8_t *dst = (uint8_t *)m_channel_list + len;
        size_t move_length = getBuffRemainingBytes(src) - len;
        std::copy_n(src, move_length, dst);
    }
    m_flags = (sFlags *)((uint8_t *)(m_flags) + len); // <----- update m_flags pointer
    m_channel_list_idx__ += count;
    *m_channel_list_length += count;
    m_buff_ptr__ += len;
    return true;
}
```

I also triggered channel selection from BML and changed the flags reason code to `OPERATION_WOULD_PREVENT_BACKHAUL_OPERATION_USING_SHARED_RADIO` to make sure it works, and it does:

![image](https://user-images.githubusercontent.com/13386849/61537886-e3eb7a80-aa40-11e9-8411-fa379c8c2014.png)

2019-07-21 11:09 UTC, LiorAmram approved these changes

2019-07-21 12:58 UTC, simonbaren approved these changes

2019-07-21 15:16 UTC, merged