tlvf: missing skip tlv function
prplfoundation/prplMesh pull request #283
Opened 2019-09-11 12:36 UTC by YuriyMasechko

Where ever parsing multiap cmdu, there is need to check what is the next tlv that is needed to be parse, and then parse it, and repeat it untill the next tlv is EndOfMessage.
It may happen that cmdu handler function will receive unexpected tlv.
If such thing happens, temporary implementation can be one of:
    1.The parser function will iterate over it infinite times causing the process to stuck. This since the tlv is not added to the cmdu.
    2.The handler function may stop handling the cmdu by return statment. This means that the cmdu will be thrown.

New class tlvUnknown was added to skip unexpected tlv. Use
msg.addClass<tlvUnknown>() to skip tlv.

Signed-off-by: Yuriy Masechko <yuriy.masechko@globallogic.com>

2019-09-11 15:10 UTC, tomereli commented
Please don't use merges, we do rebase instead. See the CONTRIBUTING.md for more information on our git workflow.

2019-09-11 15:14 UTC, tomereli requested changes
1. we don't use merges in prplMesh, so please rebase -i on origin/master to remove the merge commit
2. You are missing a commit which updates the autogenerated files

2019-09-11 15:14 UTC, tomereli commented on framework/tlvf/yaml/tlvf/ieee_1905_1/tlvUnknown.yaml
> +  type:
Please put this in the same line - `type: uint8_t`

2019-09-11 15:14 UTC, tomereli commented on framework/tlvf/yaml/tlvf/ieee_1905_1/tlvUnknown.yaml
> +  data_length: uint8_t
(nitpick) You can also use "unknown length" lists for this:
```
type: uint8_t 
length: uint16_t
data: []
```

2019-09-12 08:40 UTC, tomereli approved these changes

2019-09-12 08:51 UTC, tomereli commented
Let's wait with the merge so @arnout can also review

2019-09-12 09:01 UTC, arnout requested changes
The defintion of tlvUnknown is not OK. That really has to be fixed.

The other comments are less important.

2019-09-12 09:01 UTC, arnout commented on framework/tlvf/yaml/tlvf/ieee_1905_1/tlvUnknown.yaml
> +  data_length: uint8_t
This is not correct. The only fields we know about are the type and the length fields. There is no data_length field that we can rely on.

So instead, it should be:
```
  type: uint8_t
  length: uint16_t
  data:
    _type: uint8_t
   _length: []
```

2019-09-12 09:01 UTC, arnout commented on framework/tlvf/yaml/tlvf/ieee_1905_1/tlvUnknown.yaml
> +    _type: uint16_t
This has to be `uint8_t`, otherwise it would only support an even number of bytes.

2019-09-12 09:01 UTC, arnout commented on framework/tlvf/tlvf.py
> +                    if obj_meta.is_tlv_class and param_name == MetaData.TLV_TYPE_TYPE and param_val_const:
It would be better to make this change in a separate commit, which an explanation in the commit message why it is needed.

2019-09-12 09:01 UTC, arnout commented on framework/tlvf/test/tlvf_test.cpp
> +    auto unknownTlv = msg.addClass<tlvUnknown>();
It would be more appropriate to construct a valid TLV here, because the goal is to be able to parse an actual valid TLV but without knowing which class it corresponds to. Take a simple TLV, e.g. tlvMacAddress.

2019-09-12 13:39 UTC, tomereli submitted a review, later dismissed
@arnout made valid points, so disapproving to give a chance to fix those.

2019-09-17 18:09 UTC, arnout approved these changes
I still needed to adapt to the changed tlvf (now returning uint8_t* instead of a tuple). But I've done that and rebased so it can be merged.

2019-09-17 18:09 UTC, arnout commented on framework/tlvf/test/tlvf_test.cpp
> +    }
All this should also be in the `tlvunknown != nullptr` branch.

2019-09-17 18:20 UTC, merged