agent:backhaul_manager:really parse tlvHigherLayerData
prplfoundation/prplMesh pull request #286
Opened 2019-09-12 12:44 UTC by CoralMalachi

Fix a bug that has been added in commit d491828.

The problem is addClass is performed not on the right CMDU, but on an
empty CMDU, which causes the payload length to be zero.

Therefore, perform the addClass method on the right CMDU.

Signed-off-by: Coral Malachi <coral.malachi@intel.com>

2019-09-12 12:45 UTC, tomereli submitted a review, later dismissed

2019-09-12 12:45 UTC, tomereli commented on agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp
> +    const auto protocol       = tlvHigherLayerData->protocol();
Is this related to this fix?

2019-09-12 12:51 UTC, CoralMalachi commented on agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp
> +    const auto protocol       = tlvHigherLayerData->protocol();
I wanted it to be uniform, Do you want me to split it to another commit?

2019-09-12 13:01 UTC, tomereli commented on agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp
> +    const auto protocol       = tlvHigherLayerData->protocol();
yes please

2019-09-12 13:20 UTC, arnout requested changes
Could you also extend the test so it catches this issue? I guess that matching the protocol and length in the received message should be enough. For that, it's probably also easier to put everything in one line.

Also, the commit 97e8d8e is not in master. In master, it's d491828 (due to rebase when merging, github is a bit stupid in that respect).

Finally, a commit summary that just says "Fix a bug that has been added" is not very useful. Better would be: `agent: backhaul_manager: really parse tlvHigherLayerData`, followed by the rest of you message (i.e. "Fix a bug ...".

2019-09-12 14:18 UTC, CoralMalachi commented on agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp
> +    const auto protocol       = tlvHigherLayerData->protocol();
Ok :)

2019-09-17 11:03 UTC, arnout approved these changes

2019-09-17 15:32 UTC, merged