framework: tag possible issues found while reviewing source code
prplfoundation/prplMesh pull request #538
Opened 2019-12-05 09:56 UTC by mariomaz

I have recently joined the prplMesh project as a contributor. While
reviewing source code to get familiar with it, I have found what could
possibly be some bugs.

I have created a personal development branch and added a comment close
to each such possible issue to describe it. This way it is easy to read
through all of them and decide, case by case, if they are really issues
or just rookie missunderstandings.

Signed-off-by: Mario Maz <mmazzapater@gmail.com>

2019-12-05 17:17 UTC, arnout requested changes
I have tried to respond to all of the comments. I've created a lot of new issues to take them into account.

A lot of the comments are small fixes. For such things, just create a hotfix PR that fixes them.

Thank you for this thorough review.

I'm marking the PR as request changes since it's obviously not meant for merging.

2019-12-05 17:17 UTC, arnout commented on agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp
> + */
#539

2019-12-05 17:17 UTC, arnout commented on agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp
> +             */
As briefly discussed in the arch call, backhaul link management is out of scope for prplMesh at the moment. It is true that it's a feature that is really needed, but we'll first concentrate on getting certification and a minimal usable feature set for a product. That said, we (i.e., you :-) could/should probably already create a wiki page to track our understanding of this problem.

The current backhaul manager FSM needs serious review, because it probably still contains a lot of leftovers from "active mode" (where prplMesh was responsible for bringing up the backhaul link). We decided to remove that active mode, and instead require that the backhaul link(s) are configured up front by the platform. prplMesh responsibility limits itself to steering (possibly to another radio) and enabling/disabling a link (which would be the way for doing wired/wireless link management).

Note that EasyMesh doesn't have anything to support backhaul link selection by the controller. There isn't even a way for the controller to get beacon RSSI values from a backhaul STA, except through 11k and Beacon Metrics Query. However, it may be possible to use 1905.1a messages for backhaul link selection by the controller.

2019-12-05 17:17 UTC, arnout commented on agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp
> +     */
:+1: 

#540

2019-12-05 17:17 UTC, arnout commented on agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp
> +         */
Well, it's not really harmful either, the function will just return `false`.

2019-12-05 17:17 UTC, arnout commented on agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp
> +               */
For such small improvements, it's better that you immediately create a commit/PR that fixes it instead of going through this process.

FYI, the commit message would be:

```
agent: backhaul_manager: remove redundant iface status check

There is no need to compute m_sConfig.wire_iface status back again
as the result is already in eth_link_up variable.

Signed-off-by: ...
```

2019-12-05 17:17 UTC, arnout commented on agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp
> +     */
It's a bit more complicated than that. If there are two controllers/registrars replying to the autoconfig search, we have a problem anyway, even if one of them is Multi-AP and the other one is not.

I created #541 instead.

2019-12-05 17:17 UTC, arnout commented on agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp
> +                         */
Please create a hotfix PR for this.

2019-12-05 17:17 UTC, arnout commented on agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp
> +           */
Please create a hotfix PR for this.

2019-12-05 17:17 UTC, arnout commented on agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp
> +                         */
Please create a hotfix PR for this.

2019-12-05 17:17 UTC, arnout commented on agent/src/beerocks/slave/platform_manager/bpl_loader.c
> + * maintainability are more difficult.
I fully agree. I thought that I had mentioned this in #469 but apparently not. Added there now.

2019-12-05 17:17 UTC, arnout commented on common/beerocks/bcl/include/bcl/beerocks_config_file.h
> +     * anything about the modules that depend on it.
Indeed. I've created #542 which covers this and a whole lot more.

2019-12-05 17:17 UTC, arnout commented on common/beerocks/bcl/include/bcl/beerocks_defines.h
> +   * return value, that is, not including a termination char.
Good point. Feel free to create a PR that improves this.

Ideally, however, this really should be a maximum length, and the actual length should be encoded in the messages.

Even more ideal would be a string type in tlvf for a dynamic-length string with a 1-byte length, and that can be read and written as std::string.

2019-12-05 17:17 UTC, arnout commented on common/beerocks/bcl/include/bcl/beerocks_promise.h
> +         * parameter.
Or even better, throw this thing away and replace it with std::promise and std::future. @vitalybu do you know why this wasn't done?

2019-12-05 17:17 UTC, arnout commented on common/beerocks/bcl/include/bcl/beerocks_ucc_listener.h
> +     * (detected by static source code analyzer in Eclipse)
Please create a hotfix PR for this.

2019-12-05 17:17 UTC, arnout commented on common/beerocks/bcl/include/bcl/network/net_struct.h
> + * Alternatively, move other structs so they are also autogenerated as sMacAddr
This is historicaly accident, because:

- we needed this operator for sMacAddr;
- we were too lazy to update tlvf to generate operator== for all structs (it's not so simple, and it is not needed for most of them);
- we needed a place for this operator, and we didn't want to create a new header file just for that.

2019-12-05 17:17 UTC, arnout commented on common/beerocks/bcl/source/beerocks_os_utils.cpp
> +   * then nothing will break
IMO this whole process management thing should be revisited and either rely on the system's process manager (procd, systemd) or be implemented as a single process manager to manages all of the subprocesses. That process manager could do things the right way and store PIDs in memory and use wait/waitpid() instead of relying on race-ridden PID files.

Actually, I'd prefer if prplMesh were a single multicall binary and it would plain fork() internally, instead of relying on fork-exec or the horrible system().

2019-12-05 17:17 UTC, arnout commented on common/beerocks/bcl/source/beerocks_os_utils.cpp
> +   * is already being being checked inside the close() function).
I agree that close_file is useless. Please create a hotfix PR for this.

2019-12-05 17:17 UTC, arnout commented on common/beerocks/bcl/source/beerocks_socket_thread.cpp
> +           * server socket to a particular interface?
This is only used in the CLI and the certification agent, both of which are meant for external access, so yes this is intentional.

(Never mind the use in mrouter; @morantr will remove that soon.)

2019-12-05 17:17 UTC, arnout commented on common/beerocks/bcl/source/beerocks_socket_thread.cpp
> +    // eventually received if iterating.
To be honest, there's a lot more wrong with this code... For example, if the length is larger than the buffer, no recv() is done, so the bytes aren't abandoned, so you've essentially DoS'ed the socket...

2019-12-05 17:17 UTC, arnout commented on common/beerocks/bcl/source/beerocks_socket_thread.cpp
> +                 * returns. So rx_buffer should not be an argument of custom_message_handler
The rx buffer is just used as buffer space in custom_message_handler, to avoid the need for allocating a separate buffer there. The contents are immediately overwritten by a call to readBytes.

2019-12-05 17:17 UTC, arnout commented on common/beerocks/bcl/source/beerocks_ucc_listener.cpp
> +         * MMZ redundant code
Please create a hotfix PR for this.

2019-12-05 17:17 UTC, arnout commented on common/beerocks/bcl/source/beerocks_ucc_listener.cpp
> +     * the end of buffer
Please create a hotfix PR for this.

2019-12-05 17:17 UTC, arnout commented on common/beerocks/bcl/source/network/socket.cpp
> + * the method signature itself
Please create a hotfix PR for this.

2019-12-05 17:17 UTC, arnout commented on common/beerocks/bcl/source/network/socket.cpp
> +   * MMZ: Windows code should be removed for better readability
#544

2019-12-05 17:17 UTC, arnout commented on common/beerocks/bcl/source/network/socket.cpp
> +     * MMZ Should be != instead of ==
Please create a hotfix PR for this. Actually the condition is redundant.

I wonder how we didn't notice before...

2019-12-05 17:17 UTC, arnout commented on common/beerocks/bcl/source/network/socket.cpp
> +    // be read, one after the other. This case should not be considered an error
No, if buf_len is set, then it is the size of one message, so it should never be bigger than the buffer size. If buf_len is not set, it will be set equal to buf_size above so the condition will not be true.

2019-12-05 17:17 UTC, arnout commented on common/beerocks/bcl/source/beerocks_ucc_listener.cpp
> +     * be treated as if just one command had been received, others being ignored
In practice, no, because UCC doesn't send another command until a reply is received for the previous one.

2019-12-05 17:17 UTC, arnout commented on common/beerocks/btl/btl_local_bus.cpp
> +         * ret = ret && ...
Please create a hotfix PR for this. Indeed, if one of them fails we're dead anyway so it doesn't make sense to continue.

Actually, there's no real reason to use `for_each` here, a ranged for loop with a `return false` on failure  would be simpler.

2019-12-05 17:17 UTC, arnout commented on common/beerocks/btl/btl_uds.cpp
> +// MMZ No need to reimplement this method because behavior is the same
Please create a hotfix PR for this.

2019-12-05 17:17 UTC, arnout commented on common/beerocks/btl/btl_uds.cpp
> +// MMZ No need to reimplement this method because behavior is the same
Please create a hotfix PR for this.

2019-12-05 17:17 UTC, arnout commented on common/beerocks/btl/btl_uds.cpp
> +// MMZ No need to reimplement this method because behavior is the same
Please create a hotfix PR for this.

2019-12-05 17:17 UTC, arnout commented on common/beerocks/btl/btl_uds.cpp
> +     * MMZ: This method is copy&paste of socket_thread::work() (the one at base class)
Please create a hotfix PR for this.

2019-12-05 17:17 UTC, arnout commented on common/beerocks/btl/include/btl/btl.h
> +    // MMZ: cmdu parameter should be const&
Please create a hotfix PR for this. It will require making come methods of CmduMessage const as well though.

2019-12-05 17:17 UTC, arnout commented on common/beerocks/tlvf/src/src/beerocks_message.cpp
> +     * and parse() methods would always swap bytes)
:+1: 

Actually, I think the swapping should even be done immediately while writing the values. But that's a bit a bigger change... #547

2019-12-05 17:17 UTC, arnout commented on framework/common/include/mapf/common/socket.h
> +     * const reference
Please create a hotfix PR for this.

2019-12-05 17:17 UTC, arnout commented on framework/common/include/mapf/common/socket.h
> +         */
This function is actually unused. I'm surprised though that gcc doesn't warn about it (and -Werror is turned on...)

Please create a hotfix PR for this.

2019-12-05 17:17 UTC, arnout commented on framework/common/include/mapf/common/socket.h
> +         */
Also unused.

2019-12-05 17:17 UTC, arnout commented on framework/discovery_agent/include/mapf/topology_discovery_agent/topology_discovery_agent.h
> +     * MMZ This structure is defined several times in the project
topology_discovery is not built at the moment and hasn't been kept up to date.

These comments are definitely very helpful for reviving topology_discovery:
#300

2019-12-05 17:17 UTC, arnout commented on framework/tlvf/src/src/CmduMessageRx.cpp
> +     * Why using a list of parsers? It seems like just one parser should suffice
I had the same feedback but the PR got merged regardless :-)

Should be fixed soon by @CoralMalachi and @Galvien as part of #318 #471 #160

2019-12-05 17:17 UTC, arnout commented on framework/tlvf/yaml/tlvf/ieee_1905_1/tlvDeviceInformation.yaml
> +# n octets: Media-specific information of the local interface (as defined in the "Media-specific information" column of Table 6-12.
Many of the IEEE1905.1 structures are currently unused. Some of them will be revived and corrected as part of #300.

2019-12-05 17:17 UTC, arnout commented on framework/transport/ieee1905_transport/include/mapf/transport/ieee1905_transport_messages.h
> +     * renamed to avoid confusion)
I think @CoralMalachi will push a PR soon that fixes this.

2019-12-05 18:15 UTC, vitalybu commented on common/beerocks/bcl/include/bcl/beerocks_promise.h
> +         * parameter.
It was created to workaround a bug in some older GCC compiler (probably 4.7-4.8).
The standard future/promise implementations caused a deadlock in some cases.

2019-12-05 18:17 UTC, vitalybu commented on common/beerocks/bcl/source/beerocks_os_utils.cpp
> +   * then nothing will break
👍

2019-12-05 23:03 UTC, tomereli commented on common/beerocks/bcl/source/beerocks_socket_thread.cpp
> +    // eventually received if iterating.
True - we should check if the message_size is smaller than the size of the buffer. But other than that (edge case) - its a blocking read, we know from the UDS header *exactly* how many bytes are there to read, so we try to read all of them.
I don't see an issue here.. @vitalybu , your thoughts?

2019-12-06 11:19 UTC, vitalybu commented on common/beerocks/bcl/source/beerocks_socket_thread.cpp
> +    // eventually received if iterating.
The socket is not read only when the number of available bytes is less than the size of the UDS header.
`recv()` is always called inside `readBytes()` (data is truncated to the buffer size).
Not sure I understand the issue here...

2019-12-06 13:00 UTC, arnout commented on common/beerocks/bcl/include/bcl/beerocks_promise.h
> +         * parameter.
Could we require GCC 4.9+ and change it to std::future/promise then?

2019-12-06 13:46 UTC, tomereli commented on common/beerocks/bcl/include/bcl/beerocks_promise.h
> +         * parameter.
I think we can, UGW8.x and RDKB toolchains both >4.9 so I don't see an issue with that.

2019-12-06 14:22 UTC, vitalybu commented on common/beerocks/bcl/include/bcl/beerocks_promise.h
> +         * parameter.
Yup

2019-12-06 14:42 UTC, arnout commented on common/beerocks/bcl/source/beerocks_socket_thread.cpp
> +    // eventually received if iterating.
> its a blocking read, we know from the UDS header _exactly_ how many bytes are there to read, so we try to read all of them.

No we don't. There's only a single recv(). If the full packet has not been received yet, recv() will return with a length that is smaller than the full packet. So the recv() should be continued in a loop until the full packet is received.

However, in practice, this cannot happen:

- UDS on Linux will transport everything passed to send() atomically (at least up to 4K, but I think even it is bigger), and we always send the full CMDU with one send();
- IEEE1905 and LLDP frames from the network fit in a single Ethernet packet, and that is passed up to recv() in a single chunk.

2019-12-06 14:57 UTC, closed without merging