Feature/add prpl to initd and run as nwk user
prplfoundation/prplMesh pull request #607
Opened 2019-12-24 16:57 UTC by adam1985d

- [ ] add start_wait function that performs start() and waits for any  child process exit (this enables the 'procd' watchdog/respawn feature)
- [ ] add repeater support in start() implementation
- [ ] fix log typo

2019-12-25 08:05 UTC, tomereli commented on common/beerocks/scripts/prplmesh_utils.sh.in
> +        SA_RPT | sa_rpt)
I'd call it AP (Agent Proprietary)

2019-12-25 08:09 UTC, tomereli requested changes
prplmesh_platform_db_init is only used for Dummy mode (Linux). We don't need to support this mode in linux, it shouldn't be part of this script and you should simply set this in UCI and call the regular start -A option.
The UGW/RDKB/NH init script shouhld take care of setting the UCI DB to "Proprietary-Mesh" and "WDS-Repeater" and then should simply run `/opt/prplmesh/prplmesh_utils.sh start -m A`

2019-12-25 16:28 UTC, kantera800 commented on common/beerocks/scripts/prplmesh_utils.sh.in
> +        SA_RPT | sa_rpt)
removed

2019-12-25 20:20 UTC, tomereli approved these changes

2019-12-26 09:12 UTC, tomereli approved these changes

2019-12-26 09:13 UTC, merged