Feature/vap list for backhaul
prplfoundation/prplMesh pull request #608
Opened 2019-12-26 09:54 UTC by YuriyMasechko

Each son slave sends a VAP list update to the controller once the VAPs are read. Send this VAP list update also to the backhaul, with the RUID. This will be used to store the VAPs configuration in the UCC listener so it can use it to answer `dev_get_parameter` from the UCC.

2019-12-29 09:25 UTC, tomereli requested changes
https://github.com/prplfoundation/prplMesh/pull/608/commits/9548ade76570ae6f59310f60c1cde18ee51e2ba0 should be split to 2 - one commit which adds the message passing from son slave to the backhaul and just prints that the VAP configuration update received in the backhaul manager, and one which adds the actual map and updates it. But I guess it's a nitpick.

2019-12-29 09:25 UTC, tomereli commented on agent/src/beerocks/slave/agent_ucc_listener.cpp
> +} sVapElement;
Missing line break

2019-12-29 09:52 UTC, tomereli approved these changes

2019-12-29 09:53 UTC, merged

2020-01-02 12:05 UTC, morantr commented on agent/src/beerocks/slave/agent_ucc_listener.cpp
> +} sVapElement;
Why did you define `sVapElement`  and not using it?

2020-01-02 12:05 UTC, morantr commented on agent/src/beerocks/slave/agent_ucc_listener.cpp
> +    vaps_map[ruid] = vaps;
Besides to insert data into the container, there is no use for it.

2020-01-02 12:06 UTC, morantr commented
This PR is partial, I don't think it should have been merged.