[KW]: Resolve nullptr issue
prplfoundation/prplMesh pull request #645
Opened 2020-01-06 17:45 UTC by CoralMalachi

After running the klocwork script on RDKB with prplMesh, the following error was received :

" Pointer *** returned from call to function *** may be NULL and will be dereferenced at ... "

To solve this error, add a check to validate that the return value of `create_vs_message`
method is not nullptr.

Signed-off-by: CoralMalachi <coral.malachi@intel.com>

2020-01-06 18:54 UTC, tomereli commented on agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp
> +        if (register_response == nullptr) {
`if (!register_response)`?

2020-01-06 18:55 UTC, tomereli requested changes
Didn't we say that KW complains when we compare to nullptr instead of `if (!ptr)`? even if in this case it doesn't, I still think we should align our code to one convention.

2020-01-06 18:55 UTC, tomereli commented on agent/src/beerocks/slave/backhaul_manager/backhaul_manager_thread.cpp
> +        if (notification == nullptr) {
same here

2020-01-07 08:39 UTC, CoralMalachi commented
> Didn't we say that KW complains when we compare to nullptr instead of `if (!ptr)`? even if in this case it doesn't, I still think we should align our code to one convention.

Yes, but we also decided to ignore this issue. if we change it here we need to change everywhere we use it. BTW, the in case of failure, `create_vs_message` return a nullptr so comparing it to nullptr looks correct to me.

2020-01-07 13:15 UTC, tomereli approved these changes

2020-01-07 13:17 UTC, merged

2020-01-08 12:41 UTC, arnout commented
> > Didn't we say that KW complains when we compare to nullptr instead of `if (!ptr)`? even if in this case it doesn't, I still think we should align our code to one convention.
> 
> Yes, but we also decided to ignore this issue. if we change it here we need to change everywhere we use it.

The original idea of #611 was indeed to replace all `foo == nullptr` with `!foo`, and you had already done that work. So why did we change our mind?