Update issue templates
prplfoundation/prplMesh pull request #65
Opened 2019-06-26 09:55 UTC by tomereli

Add issue templates

2019-06-27 10:21 UTC, arnout requested changes
If we add this, we better get this right...

The commit subject is incorrect: it's not "Update", it's "Add".

CONTRIBUTING.md says that there should be a component, in this case I guess its "github".

2019-06-27 10:21 UTC, arnout commented on .github/ISSUE_TEMPLATE/bug_report.md
> + - OS: [e.g. Linux DUMMY mode with ZMQ]
```suggestion

 - Host: [e.g. Ubuntu 18.04]
 - Platform: [e.g. Linux DUMMY mode with ZMQ]
```

2019-06-27 10:21 UTC, arnout commented on .github/ISSUE_TEMPLATE/feature-development.md
> +assignees: ''
Shouldn't we add milestone here? And maybe default it to `Certifiable controller on Ubuntu NUC` (the milestone I added already).

2019-06-27 10:21 UTC, arnout commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**To Reproduce**
Isn't it more appropriate to use a heading here?
```suggestion
## To Reproduce
```

Note that the **Describe the bug** doesn't need to be a heading IMO.

2019-06-27 10:21 UTC, arnout commented on .github/ISSUE_TEMPLATE/bug_report.md
> +1. Build
Your md-lint said that there should be an empty line before this :-)

2019-06-27 10:21 UTC, arnout commented on .github/ISSUE_TEMPLATE/bug_report.md
> +2. Run controller & Agent
```suggestion
2. Run controller & agent
```

2019-06-27 10:21 UTC, arnout commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**Expected behavior**
```suggestion
## Expected behavior
```

2019-06-27 10:21 UTC, arnout commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**Screenshots**
```suggestion
## Screenshots
```

2019-06-27 10:21 UTC, arnout commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**Target (please complete the following information):**
```suggestion
## Target
**(please complete the following information)**
```

2019-06-27 10:21 UTC, arnout commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**Additional context**
```suggestion
## Additional context
```

2019-06-27 10:21 UTC, arnout commented on .github/ISSUE_TEMPLATE/feature-development.md
> +title: "[FEATURE]"
I would call it a task. So
```
name: Task
title: "[TASK]"
```

2019-06-27 12:54 UTC, tomereli commented
> If we add this, we better get this right...
> 
> The commit subject is incorrect: it's not "Update", it's "Add".
> 
> CONTRIBUTING.md says that there should be a component, in this case I guess its "github".

don't know how to fix the commit message without force push, so i'll do that at the final rebase before merge.

2019-06-27 13:14 UTC, tomereli commented on .github/ISSUE_TEMPLATE/feature-development.md
> +title: "[FEATURE]"
I changed this a lot, see fixup commit

2019-06-28 10:35 UTC, arnout approved these changes

2019-06-28 11:01 UTC, merged