CONTRIBUTING.md: add a comment about the "MergeWhenReady" tag
prplfoundation/prplMesh pull request #800
Opened 2020-02-10 13:14 UTC by rmelotte

Added a comment about the usage of the "[merge when ready](https://github.com/apps/mergewhenready)" feature.

2020-02-10 13:47 UTC, arnout requested changes

2020-02-10 13:47 UTC, arnout commented on CONTRIBUTING.md
> +You can add the "MergeWhenReady" tag, and Github will automatically merge the pull request once the CI has finished and is passing.
Actually, my idea was to remove the use of the "don't merge" tag completely, and instead rely on the MergeWhenReady tag to mark it as ready to merge. So it's a bit more invasive change to our workflow.

2020-02-10 18:11 UTC, tomereli commented
Seems that this feature is not working..

2020-02-10 20:33 UTC, rmelotte commented
[This issue](https://github.com/fossapps/MergeWhenReady/issues/2) mentions the tag has to be added /after/ the PR has the required review (which is accidentally the workflow I had in mind and that s described in the PR).
We can try again by adding the tag after the reviews.

2020-02-11 07:47 UTC, rmelotte commented
If it still doesn't work we could also try this one, it looks more actively maintained, and also more flexible:
https://github.com/palantir/bulldozer#deployment

2020-02-12 08:58 UTC, morantr approved these changes

2020-02-12 13:09 UTC, arnout commented
> If it still doesn't work we could also try this one, it looks more actively maintained, and also more flexible:
> https://github.com/palantir/bulldozer#deployment

Although it looks interesting, it seems to require us to set up a server that can be reached by github... That's a bit too much IMO.

@tomereli found the [merge-me action](https://github.com/marketplace/actions/merge-me). That looks promising. I'll give it a go.

BTW I tried another PR with the workflow: get two approvals, push a new version, while building add the tag -> still didn't work.

2020-02-12 13:13 UTC, arnout commented
Looking at the merge-me action: it also seems pretty heavyweight. I don't know if it's really worth the trouble...

2020-02-21 12:29 UTC, arnout commented
Mergify is now enabled, and has a different workflow (no MergeWhenReady tag, it's automatic). So closing this PR.

2020-02-21 12:29 UTC, closed without merging