WIP: tools: added test for prplmesh operational status
prplfoundation/prplMesh pull request #83
Opened 2019-07-03 08:00 UTC by slyusar003

2019-07-03 09:35 UTC, tomereli requested changes

2019-07-03 09:35 UTC, tomereli commented on .travis.yml
> +  - sudo ./test.sh test -c start --skip-platform
```suggestion
sudo ./run.sh start-controller-agent -d -n cont
sudo docker container exec -it cont <path to install>/scripts/prplmesh_utils.sh status
```

2019-07-03 09:35 UTC, tomereli commented on common/CMakeLists.txt
> +    add_definitions(-DBEEROCKS_LINUX)
Why do you need to add CFLAG here? `BEEROCKS_LINUX`

2019-07-03 09:35 UTC, tomereli commented on tools/docker/builder/Dockerfile
> +	net-tools \
This is a builder dockerfile - please don't change it, you should use the runner dockerfile for testing

2019-07-03 09:35 UTC, tomereli commented on tools/docker/README.md
> -The docker builder image can be used to build prplMesh via `maptools.py build` command running in a prplmesh-build container via `build.sh`.
builder docker should remain only for build. You have runner docker for anything else.

2019-07-03 09:35 UTC, tomereli commented on tools/docker/test.sh
> +    run docker container run -u root -v ${topdir}:${topdir} --interactive --tty --rm prplmesh-build $@
simply use prplmesh-runner instead here, but also base this script on run.sh which added some more capabilities (maybe you need to rebase)

2019-07-04 10:26 UTC, tomereli requested changes

2019-07-04 10:26 UTC, tomereli commented on .travis.yml
> +  # - sudo ./test.sh test -c status
remove commented out call

2019-07-04 10:26 UTC, tomereli commented on tools/commands/test.py
> +import logging
Just out of curiosity, why do we need this command at all now that prplmesh_utils.sh provides all this?

2019-07-04 10:26 UTC, tomereli commented on tools/docker/test.sh
> +#!/bin/sh
This script is not needed any more

2019-07-06 09:31 UTC, arnout commented
This PR has been superseded by #92

2019-07-06 09:31 UTC, closed without merging