documentation: test_flows.py test description
prplfoundation/prplMesh pull request #980
Opened 2020-03-17 11:59 UTC by abelog

There is no description of test which are done in test_flows.py.
So none has confirmed info about test_flows.py -> Cert test mapping
and general overview of tests are missing.

General intention of this PR is to form up such document in form of `README.md`
in `tests`section. As i am collecting info on it for F2C presentation.

2020-04-01 13:11 UTC, arnout requested changes
I guess the idea is to squash everything in a single commit before applying? If not, I think you should. The individual commits have little merit and just pollute the history. If you plan on squashing commits, it's a good idea to make sure at least one commit has no Signed-off-by tag - that way, you're sure the merging is blocked until you actually squashed it, because the DCO check will fail. Also, to allow reviewers to validate the commit message as well as the change itself, it's convenient to:
- use fixup commits whenever you don't change the commit message;
- use squash commits with the full new commit message when you do change the commit message;
- (optionally) point out you did this in the PR comments.

Like for #965, I'm going to mark this as changes requested and re-review when the commit messages are updated.

2020-04-01 13:11 UTC, arnout commented on tests/README.md
> +### ...
What is this?

2020-04-01 13:11 UTC, arnout commented on tests/README.md
> +- check log repeater 1 agent TOPOLOGY_QUERY_MESSAGE
I didn't review all of the above -- too boring. I am a bit unsure what value it adds, it seems pretty easy to get the same information by just looking at the source code...

2020-04-01 13:11 UTC, arnout commented on tests/README.md
> +| 4.2.1 MAUT §5 Multi-AP Ethernet Onboarding and Initialization test | (channel_selection)
Maybe we should explicitly indicate the step(s) that are covered by a particular flow.

Maybe we should abbreviate the certification test description a little (can be done with a simple search-replace: `M[AC]UT §[^ ]* Multi-AP ` to nothing; `test |` -> `|`).

```suggestion
| 4.2.1 Ethernet Onboarding and Initialization | step 1-9: -<br>step 10: channel_selection<br>step 11-12: (topology) |
```

Note that (after #965 is merged) I think the channel selection test covers step 10 completely, so no parenthesis any more.

That said, I think we can merge it as is now and fill in details later. Just one or two examples that are worked out in detail to show the direction we want to go to.

2020-04-03 14:46 UTC, MuteSpirit commented on tests/README.md
> +### ...
Removed

2020-04-03 14:54 UTC, MuteSpirit commented on tests/README.md
> +- check log repeater 1 agent TOPOLOGY_QUERY_MESSAGE
Agree
But i suggest to not delete it right now and not broke document structure

2020-04-03 14:55 UTC, MuteSpirit commented on tests/README.md
> +| 4.2.1 MAUT §5 Multi-AP Ethernet Onboarding and Initialization test | (channel_selection)
Apply your code suggestion
And add similar test steps cover description for 4.3.2

2020-04-07 12:54 UTC, arnout approved these changes
You'll also need to change the commit message after squashing the two commits. Everything after the first paragraph can be removed IMO. Oh, and keep two signoffs, both Anton's and Ivan's.

2020-04-08 07:38 UTC, VladyslavTupikin approved these changes

2020-04-08 10:07 UTC, merged