Hotfix/fix reconnect of son slave on topology flow
prplfoundation/prplMesh pull request #994
Opened 2020-03-22 19:43 UTC by morantr

2020-03-22 21:29 UTC, tomereli approved these changes

2020-03-23 06:18 UTC, kantera800 requested changes
@morantr 
The original problem was spotted on UGW so we need to test this fix there also.
In addition please perform the following test:
->kill the monitor process manually 
->check if agent restarts it

adding the don't merge flag until then

2020-03-23 09:42 UTC, morantr commented
> @morantr
> The original problem was spotted on UGW so we need to test this fix there also.
> In addition please perform the following test:
> ->kill the monitor process manually
> ->check if agent restarts it
> 
> adding the don't merge flag until then

passed

2020-03-23 12:14 UTC, arnout approved these changes
The second commit message doesn't convey anything useful. The change is not related at all to commit 10f137c - that commit changed the return of fill_radio_iface_info, and only in one specific case; here you're changing the return of handle_1905_topology_query.

A better commit message:

```
agent: handle_topology_query(): return true also on failure

If a handle_... function returns false, it means that the message will be forwarded
to the slaves. That's not what we want here, so always return true.
```

However, with this reasoning, we should return true *everywhere*. Indeed, except for maybe one or two cases, if the message has a handle function, it really shouldn't be forwarded.

So I think a better solution would be to add an addition argument to handle_1905_1_message() and use that to indicate if it needs to be forwarded or not. If the function returns false, it's an error so you don't forward. If it returns true, you check the forward_to_slaves value and if true you forward. What do you think?

2020-03-23 13:18 UTC, morantr commented
> The second commit message doesn't convey anything useful. The change is not related at all to commit [10f137c](https://github.com/prplfoundation/prplMesh/commit/10f137c235a0e9a26142617b63e33609ca46d0c7) - that commit changed the return of fill_radio_iface_info, and only in one specific case; here you're changing the return of handle_1905_topology_query.
> 
> A better commit message:
> 
> ```
> agent: handle_topology_query(): return true also on failure
> 
> If a handle_... function returns false, it means that the message will be forwarded
> to the slaves. That's not what we want here, so always return true.
> ```
> 
> However, with this reasoning, we should return true _everywhere_. Indeed, except for maybe one or two cases, if the message has a handle function, it really shouldn't be forwarded.
> 
> So I think a better solution would be to add an addition argument to handle_1905_1_message() and use that to indicate if it needs to be forwarded or not. If the function returns false, it's an error so you don't forward. If it returns true, you check the forward_to_slaves value and if true you forward. What do you think?

I don't think we should put effort into that since when we will create the unified Agent, all of this will be moved to there, and no forwarding will be done.

2020-03-23 13:51 UTC, kantera800 approved these changes

2020-03-23 15:37 UTC, arnout commented
@morantr @kantera800 Remember it is now not sufficient any more to remove the don't merge tag, you also have to set the Ready for merge tag if you want mergify to proceed.

I merged manually now.

2020-03-23 15:37 UTC, merged